name: transcendance
channels:
  - defaults
dependencies:
  - asgiref=3.10.0=py314hca03da5_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - django=5.2.8=py314hca03da5_0
  - libcxx=20.1.8=hd7fd590_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libmpdec=4.0.0=h80987f9_0
  - libzlib=1.3.1=h5f15de7_0
  - lz4-c=1.9.4=h313beb8_1
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyh0d26453_0
  - python=3.14.2=h1858270_101_cp314
  - python_abi=3.14=2_cp314
  - readline=8.3=h0b18652_0
  - sqlite=3.51.0=hab6afd1_0
  - sqlparse=0.5.3=py314hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - django-extensions==4.1
      - django-filter==25.2
      - djangorestframework==3.16.1
      - markdown==3.10
      - pydot==4.0.1
      - pyparsing==3.3.1
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/transcendance
