
target-version = "py311"
line-length = 88

lint.select = ["E", "F", "D", "ANN", "I", "UP", "B", "SIM", "N", "PTH"]

lint.ignore = [
    "D203",
    "D213",
]

[lint.pydocstyle]
convention = "google"

[lint.flake8-annotations]
allow-star-arg-any = true

ignore-fully-untyped = false