name: backend
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.12.1
  - asgiref=3.10.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - dav1d=1.2.1
  - django=5.2.8
  - expat=2.7.3
  - fontconfig=2.15.0
  - freetype=2.14.1
  - fribidi=1.0.16
  - graphite2=1.3.14
  - harfbuzz=12.3.0
  - icu=73.1
  - jpeg=9f
  - lcms2=2.17
  - ld_impl_linux-aarch64=2.44
  - lerc=4.0.0
  - libavif=1.3.0
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libglib=2.86.3
  - libgomp=15.2.0
  - libiconv=1.16
  - libmpdec=4.0.0
  - libopenjpeg=2.5.4
  - libpng=1.6.54
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=1.41.5
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - ncurses=6.5
  - openssl=3.0.18
  - pcre2=10.46
  - pillow=12.1.0
  - pip=25.3
  - pixman=0.46.4
  - pthread-stubs=0.3
  - python=3.14.2
  - python_abi=3.14
  - readline=8.3
  - sqlite=3.51.1
  - sqlparse=0.5.3
  - tk=8.6.15
  - tzdata=2025c
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - attrs==25.4.0
      - django-cors-headers==4.9.0
      - django-extensions==4.1
      - django-rest-framework==0.1.0
      - djangorestframework==3.16.1
      - djangorestframework-simplejwt==5.5.1
      - drf-spectacular==0.29.0
      - inflection==0.5.1
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - pyjwt==2.10.1
      - python-dotenv==1.2.1
      - pyyaml==6.0.3
      - referencing==0.37.0
      - rpds-py==0.30.0
      - uritemplate==4.2.0
prefix: /opt/conda/envs/backend