services:
  backend:
    container_name: backend
    image: transcendence-backend
    build: ./backend
    volumes:
      - backend-db:/app/db.sqlite3
    environment:
      - DEBUG=True
      - SECRET_KEY=change-me
    # Remove for production
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
  nginx:
    container_name: nginx
    image: transcendence-nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  backend-db:
