services:
  backend:
    container_name: backend
    image: transcendence-backend
    build: ./backend/
    volumes:
      - ./backend/DB:/backend/DB/
    ports:
      - "8000:8000"
    env_file: ./backend/.env

  nginx:
    container_name: nginx
    image: transcendence-nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  backend-db:
